services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: jianroot
      MONGO_INITDB_ROOT_PASSWORD: jian123
      MONGO_INITDB_DATABASE: todos
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_logs:/var/log/mongodb
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: always
  api-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-app
    environment:
      MONGO_URI: mongodb://jian:jian123@mongodb:27017/todos
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    restart: always

volumes:
  mongodb_data:
    driver: local
  mongodb_logs:
    driver: local

